// Export these to be used elsewhere
pub use riscv::interrupt::{Exception, Interrupt as CoreInterrupt};
use riscv_rt::{ExceptionNumber, InterruptNumber};
pub use riscv_rt::{TrapFrame, core_interrupt, exception, external_interrupt};

/// ExternalInterrupts are generated by the SAR and RTC_IO peripherals,
/// and are dispatched when a MachineExternal interrupt is fired.
#[allow(missing_docs)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[riscv::pac_enum(unsafe ExternalInterruptNumber)]
pub enum ExternalInterrupt {
    SensInterrupt = 0,
    GpioInterrupt = 1,
}

#[doc(hidden)]
#[unsafe(link_section = ".ulp_trap.rust")]
#[inline(always)]
pub fn ulp_setup_interrupts() {
    mie_impl(true);
}

#[doc(hidden)]
#[inline(always)]
#[unsafe(link_section = ".ulp_trap.rust")]
pub fn mie_impl(enable: bool) -> bool {
    // Does not affect the internal exception bits,
    //  which are always enabled (unmasked, value here is 0).
    // IRQ Type   Bit   Description
    // Internal     0   Internal timer interrupt
    // Internal     1   EBREAK/ECALL or Illegal Instruction
    // Internal     2   BUS Error (Unaligned Memory Access)
    // External    31   RTC peripheral interrupts
    let old_mask: u32;

    // let disable_exceptions: u32 = 0b111;
    let disable_bit: u32 = 1 << 31;

    // Create the new IRQ disable mask.
    // We will only change bit 31 in response to the enable boolean.
    // i.e. exceptions will always be enabled.
    let new_mask: u32 = if enable { 0b0 } else { disable_bit };

    unsafe {
        core::arch::asm!(
            "maskirq_insn {}, {}",
            out(reg) old_mask,
            in(reg) new_mask
        );
    }

    // Return previous enabled value,
    // where enable == 0 (unmasked)
    (old_mask & disable_bit) == 0
}

/// Converts an IRQ bitmask value into a riscv-rt-compatible
/// interrrupt::Trap type (Interrupt or Exception).
#[inline(always)]
#[unsafe(link_section = ".ulp_trap.rust")]
pub fn irq_to_mcause(cause: u32) -> Option<riscv::interrupt::Trap<usize, usize>> {
    // IRQ Type   Bit   Description                             Result
    // Internal     0   Internal timer interrupt                Interrupt::MachineTimer
    // Internal     1   EBREAK/ECALL or Illegal Instruction     Exception::IllegalInstruction
    // Internal     2   BUS Error (Unaligned Memory Access)     Exception::LoadMisaligned
    // External    31   RTC peripheral interrupts               Interrupt::MachineExternal

    // The mcause register does not exist on the riscv ULP cores,
    // so the Trap IRQ mask is read from custom register Q1.
    // This is done in the _ulp_start_trap assembly function.

    if cause & (1 << 31) != 0 {
        return Some(riscv::interrupt::Trap::Interrupt(
            CoreInterrupt::MachineExternal.number(),
        ));
    }

    if cause & (1 << 0) != 0 {
        return Some(riscv::interrupt::Trap::Interrupt(
            CoreInterrupt::MachineTimer.number(),
        ));
    }

    if cause & (1 << 1) != 0 {
        return Some(riscv::interrupt::Trap::Exception(
            Exception::IllegalInstruction.number(),
        ));
    }

    if cause & (1 << 2) != 0 {
        return Some(riscv::interrupt::Trap::Exception(
            Exception::LoadMisaligned.number(),
        ));
    }

    None
}

#[doc(hidden)]
#[unsafe(link_section = ".ulp_trap.rust")]
#[unsafe(export_name = "_ulp_start_trap_rust")]
pub unsafe extern "C" fn ulp_start_trap_rust(trap_frame: *const TrapFrame, irqs: u32) {
    unsafe extern "C" {
        // These functions are provided by the riscv-macros crate:
        // https://github.com/rust-embedded/riscv/blob/b3a70b7945f229e828d87dbd7e003cec291db23a/riscv-macros/src/riscv.rs#L242
        fn _dispatch_core_interrupt(code: usize);
        fn _dispatch_exception(trap_frame: *const TrapFrame, code: usize);
    }

    unsafe {
        // Convert the irq bitmask to a riscv Trap type, and then call the _dispatch functions,
        // which will then delegate to the `__EXCEPTIONS`, `__CORE_INTERRUPTS`, or
        // '__EXTERNAL_INTERRUPTS' arrays.
        if let Some(mcause) = irq_to_mcause(irqs) {
            // Handle the trap
            match mcause {
                riscv::interrupt::Trap::Interrupt(code) => _dispatch_core_interrupt(code),
                riscv::interrupt::Trap::Exception(code) => _dispatch_exception(&*trap_frame, code),
            }
        }
    }
}

// Defined below, maps ULP-registers into ExternalInterrupt codes,
// fired when a MachineExternal interrupt is triggered. Advanced users
// may replace this function entirely, by defining their own
// core_interrupt(CoreInterrupt::MachineExternal) handler function.
#[doc(hidden)]
#[unsafe(link_section = ".ulp_trap.rust")]
#[unsafe(export_name = "DefaultMachineExternalHandler")]
unsafe fn _ulp_external_interrupt_handler() {
    unsafe extern "C" {
        // This function is provided by riscv-rt, and will dispatch to the
        // handlers associated with the ExternalInterrupt enum type.
        fn _dispatch_external_interrupt(code: usize);
    }

    // At the top, read all the interrupt status regs
    let sens_int = unsafe { &*crate::pac::SENS::PTR }.sar_cocpu_int_st().read();
    let rtcio_int_st = unsafe { &*crate::pac::RTC_IO::PTR }.status().read();

    // If we got a SENS interrupt, dispatch it
    if sens_int.bits() != 0 {
        unsafe {
            _dispatch_external_interrupt(ExternalInterrupt::SensInterrupt.number());
        }
        // Clear the sens interrupt
        unsafe { &*crate::pac::SENS::PTR }
            .sar_cocpu_int_clr()
            .write(|w| unsafe { w.bits(sens_int.bits()) });
    }

    // If we got an RTC IO interrupt, dispatch it
    if rtcio_int_st.bits() != 0 {
        unsafe {
            _dispatch_external_interrupt(ExternalInterrupt::GpioInterrupt.number());
        }
        // Clear the RTC IO interrupt
        unsafe { &*crate::pac::RTC_IO::PTR }
            .status_w1tc()
            .write(|w| unsafe { w.bits(rtcio_int_st.bits()) });
    }
}
