// Export these to be used elsewhere
pub use riscv::interrupt::{Exception, Interrupt as CoreInterrupt};
use riscv_rt::{ExceptionNumber, InterruptNumber};
pub use riscv_rt::{TrapFrame, core_interrupt, exception, external_interrupt};

/// ExternalInterrupts are generated by the SAR and RTC_IO peripherals,
/// and are dispatched when a MachineExternal interrupt is fired.
#[allow(missing_docs)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[riscv::pac_enum(unsafe ExternalInterruptNumber)]
pub enum ExternalInterrupt {
    SensInterrupt = 0,
    GpioInterrupt = 1,
}

#[doc(hidden)]
#[unsafe(link_section = ".ulp_trap.rust")]
#[inline(always)]
pub fn ulp_setup_interrupts() {
    mie_impl(true);
}

/// Calls maskirq instruction to disable interrupts. Returns the previous setting.
#[inline(never)] // Never inline this, else the global ASM containing the custom isntructions won't be found.
#[unsafe(link_section = ".ulp_trap.rust")]
pub fn ulp_maskirq(disable_mask: u32) -> u32 {
    // Does not affect the internal exception bits,
    //  which are always enabled (unmasked, value here is 0).
    // IRQ Type   Bit   Description
    // Internal     0   Internal timer interrupt
    // Internal     1   EBREAK/ECALL or Illegal Instruction
    // Internal     2   BUS Error (Unaligned Memory Access)
    // External    31   RTC peripheral interrupts
    let old_mask: u32;

    unsafe {
        core::arch::asm!(
            "maskirq_insn {}, {}",
            out(reg) old_mask,
            in(reg) disable_mask
        );
    }

    old_mask
}

#[doc(hidden)]
#[unsafe(link_section = ".ulp_trap.rust")]
pub fn mie_impl(enable: bool) -> bool {
    let default_mask: u32 = 0b0;
    let ext_int_bitpos: u32 = 1 << 31;

    // Create the new IRQ disable mask.
    // We will only change bit 31 in response to the enable boolean.
    // i.e. exceptions will always be enabled.
    let new_mask: u32 = if enable {
        default_mask
    } else {
        default_mask | ext_int_bitpos
    };

    let old_mask = ulp_maskirq(new_mask);

    // Return previous enabled value,
    // where enable == 0 (unmasked)
    (old_mask & ext_int_bitpos) == 0
}

#[doc(hidden)]
#[unsafe(link_section = ".ulp_trap.rust")]
#[unsafe(export_name = "_ulp_start_trap_rust")]
pub unsafe extern "C" fn ulp_start_trap_rust(trap_frame: *const TrapFrame, irqs: u32) {
    // The mcause register does not exist on the riscv ULP cores,
    // so the Trap IRQ mask is read from custom register Q1.
    // This is done in the _ulp_start_trap assembly function, and passed in $irq argument.
    // Multiple irq bits may be set, so this function will need to check them all.

    unsafe extern "Rust" {
        pub static mut ULP_DEBUG_GLOBAL_TRAP_COUNT: u32;
        pub static mut ULP_DEBUG_GLOBAL_TRAP_CAUSE: u32;
    }

    unsafe extern "C" {
        // These functions are provided by the riscv-macros crate:
        // https://github.com/rust-embedded/riscv/blob/b3a70b7945f229e828d87dbd7e003cec291db23a/riscv-macros/src/riscv.rs#L242
        fn _dispatch_core_interrupt(code: usize);
        fn _dispatch_exception(trap_frame: *const TrapFrame, code: usize);
    }

    // IRQ Type   Bit   Description                             Result
    // Internal     0   Internal timer interrupt                Interrupt::MachineTimer
    // Internal     1   EBREAK/ECALL or Illegal Instruction     Exception::IllegalInstruction
    // Internal     2   BUS Error (Unaligned Memory Access)     Exception::LoadMisaligned
    // External    31   RTC peripheral interrupts               Interrupt::MachineExternal

    unsafe {
        ULP_DEBUG_GLOBAL_TRAP_COUNT += 1;
        ULP_DEBUG_GLOBAL_TRAP_CAUSE = irqs;
    }

    // Converts an IRQ bitmask value into a riscv-rt-compatible
    // interrrupt::Trap type (Interrupt or Exception).
    // If multiple bits in the bitmask are set,
    // handles them in order of Trap number. Exceptions first, then local interrupts, then
    // external interrupts.

    // IRQ bit 1, Exception::IllegalInstruction
    if irqs & (1 << 1) != 0 {
        unsafe { _dispatch_exception(&*trap_frame, Exception::IllegalInstruction.number()) }
    }

    // IRQ bit 2, Exception::LoadMisaligned
    if irqs & (1 << 2) != 0 {
        unsafe { _dispatch_exception(&*trap_frame, Exception::LoadMisaligned.number()) }
    }

    // IRQ bit 0, CoreInterrupt::MachineTimer
    if irqs & 1 != 0 {
        unsafe { _dispatch_core_interrupt(CoreInterrupt::MachineTimer.number()) }
    }

    // IRQ bit 31, CoreInterrupt::MachineExternal
    if irqs & (1 << 31) != 0 {
        unsafe { _dispatch_core_interrupt(CoreInterrupt::MachineExternal.number()) }
    }
}

// Defined below, maps ULP-registers into ExternalInterrupt codes,
// fired when a MachineExternal interrupt is triggered. Advanced users
// may replace this function entirely, by defining their own
// core_interrupt(CoreInterrupt::MachineExternal) handler function.
#[doc(hidden)]
#[unsafe(link_section = ".ulp_trap.rust")]
#[unsafe(export_name = "DefaultMachineExternalHandler")]
unsafe fn _ulp_external_interrupt_handler() {
    unsafe extern "C" {
        // This function is provided by riscv-rt, and will dispatch to the
        // handlers associated with the ExternalInterrupt enum type.
        fn _dispatch_external_interrupt(code: usize);
    }

    // At the top, read all the interrupt status regs
    let sens_int = unsafe { &*crate::pac::SENS::PTR }.sar_cocpu_int_st().read();
    let rtcio_int_st = unsafe { &*crate::pac::RTC_IO::PTR }.status().read();

    // If we got a SENS interrupt, dispatch it
    if sens_int.bits() != 0 {
        unsafe {
            _dispatch_external_interrupt(ExternalInterrupt::SensInterrupt.number());
        }
        // Clear the sens interrupt
        unsafe { &*crate::pac::SENS::PTR }
            .sar_cocpu_int_clr()
            .write(|w| unsafe { w.bits(sens_int.bits()) });
    }

    // If we got an RTC IO interrupt, dispatch it
    if rtcio_int_st.bits() != 0 {
        unsafe {
            _dispatch_external_interrupt(ExternalInterrupt::GpioInterrupt.number());
        }
        // Clear the RTC IO interrupt
        unsafe { &*crate::pac::RTC_IO::PTR }
            .status_w1tc()
            .write(|w| unsafe { w.bits(rtcio_int_st.bits()) });
    }
}

/// Call the custom timer instruciton on the ulp core.
/// When called, should trigger a MachineTimer interrupt after
/// <count> cycles of the ULP core.
#[inline(never)] // Never inline this, else the global ASM containing the custom isntructions won't be found.
#[unsafe(link_section = ".ulp_trap.rust")]
pub fn ulp_timer_insn(count: u32) -> u32 {
    let old_c: u32;

    unsafe {
        core::arch::asm!(
            "timer_insn {}, {}",
            out(reg) old_c,
            in(reg) count
        );
    }
    old_c
}

/// Pause execution until an interrupt becomes pending. The bitmask of pending IRQs is returned.
#[inline(never)] // Never inline this, else the global ASM containing the custom isntructions won't be found.
#[unsafe(link_section = ".ulp_trap.rust")]
pub fn ulp_wait_irq() -> u32 {
    let mut pend: u32 = 0;

    unsafe {
        core::arch::asm!(
            "waitirq_insn {}",
            out(reg) pend,
        );
    }
    pend
}
